/**
 * SensorSrvClient_PortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package lu.hitec.pss.soap.sensor.client._15_x;

public interface SensorSrvClient_PortType extends java.rmi.Remote {
    public java.lang.String[] getDevicesMissingInLdapDirectoryService(java.lang.String token) throws java.rmi.RemoteException, lu.hitec.pss.soap.sensor.client._15_x.AuthenticationException;
    public lu.hitec.pss.soap.sensor.client._15_x.LocationValue getUnitLastLocation(java.lang.String token, lu.hitec.pss.soap.sensor.client._15_x.UnitId unitId, java.lang.String missionId) throws java.rmi.RemoteException, lu.hitec.pss.soap.sensor.client._15_x.AuthenticationException;
    public lu.hitec.pss.soap.sensor.client._15_x.Project getProjectDetails() throws java.rmi.RemoteException;
    public lu.hitec.pss.soap.sensor.client._15_x.LocationRange getUnitLocationRange(java.lang.String token, lu.hitec.pss.soap.sensor.client._15_x.UnitId unitId, java.lang.String missionId, lu.hitec.pss.soap.sensor.client._15_x.RangeLimit rangeLimit) throws java.rmi.RemoteException;
    public lu.hitec.pss.soap.sensor.client._15_x.UnitsReports getAllUnitsReports(java.lang.String token, java.lang.String missionId) throws java.rmi.RemoteException, lu.hitec.pss.soap.sensor.client._15_x.AuthorizationException, lu.hitec.pss.soap.sensor.client._15_x.AuthenticationException, lu.hitec.pss.soap.sensor.client._15_x.ResourceNotFoundException;
    public lu.hitec.pss.soap.sensor.client._15_x.UnitReport[] getAllUsersReports(java.lang.String token, java.lang.String missionId) throws java.rmi.RemoteException, lu.hitec.pss.soap.sensor.client._15_x.AuthorizationException, lu.hitec.pss.soap.sensor.client._15_x.AuthenticationException, lu.hitec.pss.soap.sensor.client._15_x.ResourceNotFoundException;
    public lu.hitec.pss.soap.sensor.client._15_x.LocationStatus evaluateLocation(java.lang.String token, lu.hitec.pss.soap.sensor.client._15_x.Point location, java.lang.String missionId) throws java.rmi.RemoteException;
    public lu.hitec.pss.soap.sensor.client._15_x.UnitReport[] getAllVehiclesReports(java.lang.String token, java.lang.String missionId) throws java.rmi.RemoteException, lu.hitec.pss.soap.sensor.client._15_x.AuthorizationException, lu.hitec.pss.soap.sensor.client._15_x.AuthenticationException, lu.hitec.pss.soap.sensor.client._15_x.ResourceNotFoundException;
    public lu.hitec.pss.soap.sensor.client._15_x.ProbeRange getUnitProbeRange(java.lang.String token, lu.hitec.pss.soap.sensor.client._15_x.UnitId unitId, java.lang.String probeType, java.lang.String missionId, lu.hitec.pss.soap.sensor.client._15_x.RangeLimit rangeLimit) throws java.rmi.RemoteException;
    public lu.hitec.pss.soap.sensor.client._15_x.UnitSummary getUnitSummary(java.lang.String token, lu.hitec.pss.soap.sensor.client._15_x.UnitId unitId, java.lang.String missionId) throws java.rmi.RemoteException, lu.hitec.pss.soap.sensor.client._15_x.AuthenticationException;
    public lu.hitec.pss.soap.sensor.client._15_x.UnitReport[] getAllPlacesReports(java.lang.String token, java.lang.String missionId) throws java.rmi.RemoteException, lu.hitec.pss.soap.sensor.client._15_x.AuthorizationException, lu.hitec.pss.soap.sensor.client._15_x.AuthenticationException, lu.hitec.pss.soap.sensor.client._15_x.ResourceNotFoundException;
    public lu.hitec.pss.soap.sensor.client._15_x.ServiceLimitsImpl getServiceLimits() throws java.rmi.RemoteException;
    public lu.hitec.pss.soap.sensor.client._15_x.UnitReport[] searchUnitsByCircleZoneAndUnitType(java.lang.String token, java.lang.String missionId, lu.hitec.pss.soap.sensor.client._15_x.SimpleCircularZone circle, lu.hitec.pss.soap.sensor.client._15_x.UnitType unitType) throws java.rmi.RemoteException, lu.hitec.pss.soap.sensor.client._15_x.AuthorizationException, lu.hitec.pss.soap.sensor.client._15_x.AuthenticationException, lu.hitec.pss.soap.sensor.client._15_x.ResourceNotFoundException;
    public lu.hitec.pss.soap.sensor.client._15_x.UnitReport[] searchUnitsByPolygonZoneAndUnitType(java.lang.String token, java.lang.String missionId, lu.hitec.pss.soap.sensor.client._15_x.SimplePolygonZone polygon, lu.hitec.pss.soap.sensor.client._15_x.UnitType unitType) throws java.rmi.RemoteException, lu.hitec.pss.soap.sensor.client._15_x.AuthorizationException, lu.hitec.pss.soap.sensor.client._15_x.AuthenticationException, lu.hitec.pss.soap.sensor.client._15_x.ResourceNotFoundException;
    public lu.hitec.pss.soap.sensor.client._15_x.LocationValue getUnitLastLocationForDevice(java.lang.String token, lu.hitec.pss.soap.sensor.client._15_x.UnitId unitId, java.lang.String missionId, java.lang.String collectingDeviceId) throws java.rmi.RemoteException, lu.hitec.pss.soap.sensor.client._15_x.AuthenticationException;
    public lu.hitec.pss.soap.sensor.client._15_x.LocationRange getUnitLocationRangeForDevice(java.lang.String token, lu.hitec.pss.soap.sensor.client._15_x.UnitId unitId, java.lang.String missionId, lu.hitec.pss.soap.sensor.client._15_x.RangeLimit rangeLimit, java.lang.String collectingDeviceId) throws java.rmi.RemoteException;
    public lu.hitec.pss.soap.sensor.client._15_x.UnitsReports searchUnitsByCircleZone(java.lang.String token, java.lang.String missionId, lu.hitec.pss.soap.sensor.client._15_x.SimpleCircularZone circle) throws java.rmi.RemoteException, lu.hitec.pss.soap.sensor.client._15_x.AuthorizationException, lu.hitec.pss.soap.sensor.client._15_x.AuthenticationException, lu.hitec.pss.soap.sensor.client._15_x.ResourceNotFoundException;
    public lu.hitec.pss.soap.sensor.client._15_x.UnitsReports searchUnitsByPolygonZone(java.lang.String token, java.lang.String missionId, lu.hitec.pss.soap.sensor.client._15_x.SimplePolygonZone polygon) throws java.rmi.RemoteException, lu.hitec.pss.soap.sensor.client._15_x.AuthorizationException, lu.hitec.pss.soap.sensor.client._15_x.AuthenticationException, lu.hitec.pss.soap.sensor.client._15_x.ResourceNotFoundException;
}
