/**
 * DirectoryServiceInInterface_PortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package lu.hitec.pss.soap.ds.in._10_x;

public interface DirectoryServiceInInterface_PortType extends java.rmi.Remote {
    public void createFence(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.PssuFence fence, java.lang.String[] missionIds) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.UnauthorizedDataException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void createPlace(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.PssuPlace place, lu.hitec.pss.soap.ds.in._10_x.InternalId[] internalIds, java.lang.String[] organizations, java.lang.String[] missionIds) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.UnauthorizedDataException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException;
    public void createDevice(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.PssuDevice device, lu.hitec.pss.soap.ds.in._10_x.UnitId unitId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.UnauthorizedDataException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void createKit(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.DtoKit kit, lu.hitec.pss.soap.ds.in._10_x.UnitId unitId, java.lang.String[] equipmentIds) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.UnauthorizedDataException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void createProfile(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.DtoProfile profile, java.lang.String[] organizations, java.lang.String[] missionIds, java.lang.String[] userIds) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void createRefugee(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.DtoRefugee refugee) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.UnauthorizedDataException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException;
    public java.lang.String createMission(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.DtoMission mission, java.lang.String[] places, java.lang.String[] users, java.lang.String[] vehicles) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void updatePlace(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.PssuPlace place) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.UnauthorizedDataException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void createVehicle(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.PssuVehicle vehicle, lu.hitec.pss.soap.ds.in._10_x.InternalId[] internalIds, java.lang.String[] organizations, java.lang.String[] missionIds) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.UnauthorizedDataException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException;
    public void deleteWidget(java.lang.String token, java.lang.String widgetId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void setMyPicture(java.lang.String token, byte[] jpegPhoto) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void deleteProfile(java.lang.String token, java.lang.String profileId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void updateUser(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.PssuUser user) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void updateDevice(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.PssuDevice device) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void updateWidget(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.DtoWidget widget) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void deleteKit(java.lang.String token, java.lang.String kitId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void deleteRefugee(java.lang.String token, java.lang.String refugeeId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void deleteVehicle(java.lang.String token, java.lang.String vehicleId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void deleteUser(java.lang.String token, java.lang.String userId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void createWidget(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.DtoWidget widget) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException;
    public void updateFence(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.PssuFence fence) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void updateKit(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.DtoKit kit) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void updateMission(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.DtoMission mission) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.UnauthorizedDataException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void updateRefugee(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.DtoRefugee refugee) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void createUser(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.PssuUser user, java.lang.String[] certificationIds, lu.hitec.pss.soap.ds.in._10_x.InternalId[] internalIds, java.lang.String[] organizations, java.lang.String[] missionIds, java.lang.String[] profileIds) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.UnauthorizedDataException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void deleteFence(java.lang.String token, java.lang.String fenceId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException;
    public void updateProfile(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.DtoProfile profile) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void deletePlace(java.lang.String token, java.lang.String placeId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void deleteDevice(java.lang.String token, java.lang.String deviceId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void deleteMission(java.lang.String token, java.lang.String missionId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void updateVehicle(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.PssuVehicle vehicle) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.UnauthorizedDataException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void unAssignCertificationsFromUser(java.lang.String token, java.lang.String[] certificationIds, java.lang.String userId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void unAssignOrganizationFromProfiles(java.lang.String token, java.lang.String organization, java.lang.String[] profilesId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void unAssignInternalIdsFromEquipment(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.InternalId[] internalIds, java.lang.String equipmentId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void unAssignProfileFromOrganizations(java.lang.String token, java.lang.String profileId, java.lang.String[] organizations) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void assignMissionToUnits(java.lang.String token, java.lang.String missionId, lu.hitec.pss.soap.ds.in._10_x.UnitType unitType, java.lang.String[] ids) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void assignDeviceToUnit(java.lang.String token, java.lang.String deviceId, lu.hitec.pss.soap.ds.in._10_x.UnitId unitId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void assignFenceToMissions(java.lang.String token, java.lang.String fenceId, java.lang.String[] missionIds) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void assignKitToUnit(java.lang.String token, java.lang.String kitId, lu.hitec.pss.soap.ds.in._10_x.UnitId unitId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void createEquipment(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.DtoEquipment equipment, java.lang.String kitId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.UnauthorizedDataException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void assignMissionToFences(java.lang.String token, java.lang.String missionId, java.lang.String[] fenceIds) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public java.lang.String createCertification(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.DtoCertification certification) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException;
    public java.lang.String createOrganization(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.DtoOrganization organization) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public java.lang.String createCasualty(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.DtoCasualty casualty) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.UnauthorizedDataException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException;
    public void createResourceType(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.PssuResourceType resourceType) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.IOException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException;
    public void assignUnitToMissions(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.UnitId unitId, java.lang.String[] missionIds) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void assignEquipmentsToKit(java.lang.String token, java.lang.String[] equipmentIds, java.lang.String kitId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void assignUserToProfiles(java.lang.String token, java.lang.String userId, java.lang.String[] profileIds) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void assignProfileToUsers(java.lang.String token, java.lang.String profileId, java.lang.String[] userIds) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void createMiddleware(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.DtoMiddleware middleware) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException;
    public void updateMyAccount(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.PssuUser user) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public java.lang.String[] enableOrDisableUsers(java.lang.String token, java.lang.String[] userIds, boolean isEnable) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void deleteResourceType(java.lang.String token, java.lang.String resourceTypeId, lu.hitec.pss.soap.ds.in._10_x.ResourcesTypesEnum resourceTypeType) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void deleteCertification(java.lang.String token, java.lang.String certificationId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void deleteCasualty(java.lang.String token, java.lang.String casualtyId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void deleteOrganization(java.lang.String token, java.lang.String organizationId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void deleteMiddleware(java.lang.String token, java.lang.String middlewareId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void setPictureToEquipment(java.lang.String token, byte[] jpegPhoto, java.lang.String equipmentId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void updateCasualty(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.DtoCasualty casualty) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void updateOrganization(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.DtoOrganization organization) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void deleteEquipment(java.lang.String token, java.lang.String equipmentId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void deleteThreshold(java.lang.String token, java.lang.String thresholdId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void updateEquipment(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.DtoEquipment equipment) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void updateResourceType(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.PssuResourceType resourceType) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.IOException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void setPictureToUser(java.lang.String token, byte[] jpegPhoto, java.lang.String userId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void setPictureToMission(java.lang.String token, byte[] jpegPhotoMaybeNull, java.lang.String missionId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void updateThreshold(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.DtoThreshold threshold) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void unAssignKitFromUnit(java.lang.String token, java.lang.String kitId, lu.hitec.pss.soap.ds.in._10_x.UnitId unitId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void updateCertification(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.DtoCertification certification) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void updateMiddleware(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.DtoMiddleware middleware) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void createThreshold(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.DtoThreshold threshold) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException;
    public void assignProfileToMissions(java.lang.String token, java.lang.String profileId, java.lang.String[] missionIds) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void setPictureToOrganization(java.lang.String token, byte[] jpegPhotoMaybeNull, java.lang.String organizationId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void assignCertificationsToUser(java.lang.String token, java.lang.String[] certificationIds, java.lang.String userId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void setPrimaryLocalisationDevice(java.lang.String token, java.lang.String deviceId, lu.hitec.pss.soap.ds.in._10_x.UnitId unitId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void unAssignDeviceFromUnit(java.lang.String token, java.lang.String deviceId, lu.hitec.pss.soap.ds.in._10_x.UnitId unitId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void unAssignEquipmentsFromKit(java.lang.String token, java.lang.String[] equipmentIds, java.lang.String kitId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void unAssignFenceFromMissions(java.lang.String token, java.lang.String fenceId, java.lang.String[] missionIds) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void unAssignInternalIdsFromKit(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.InternalId[] internalIds, java.lang.String kitId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void assignInternalIdsToEquipment(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.InternalId[] internalIds, java.lang.String equipmentId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void assignInternalIdsToKit(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.InternalId[] internalIds, java.lang.String kitId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void assignMissionToProfiles(java.lang.String token, java.lang.String missionId, java.lang.String[] profileIds) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void assignOrganizationToProfiles(java.lang.String token, java.lang.String organization, java.lang.String[] profileIds) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void assignOrganizationToUnits(java.lang.String token, java.lang.String organization, lu.hitec.pss.soap.ds.in._10_x.UnitType unitType, java.lang.String[] uids) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void assignProfileToOrganizations(java.lang.String token, java.lang.String profile, java.lang.String[] organizations) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void assignInternalIdsToUnit(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.InternalId[] internalIds, lu.hitec.pss.soap.ds.in._10_x.UnitId unitId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void assignUnitToOrganizations(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.UnitId unitId, java.lang.String[] organizations) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void unAssignUnitFromMissions(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.UnitId unitId, java.lang.String[] missionIds) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void unAssignMissionFromFences(java.lang.String token, java.lang.String missionId, java.lang.String[] fenceIds) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void unAssignUserFromProfiles(java.lang.String token, java.lang.String userId, java.lang.String[] profileIds) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void unAssignMissionFromProfiles(java.lang.String token, java.lang.String missionId, java.lang.String[] profilesId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void unAssignMissionFromUnits(java.lang.String token, java.lang.String missionId, lu.hitec.pss.soap.ds.in._10_x.UnitType unitType, java.lang.String[] ids) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void unAssignProfileFromMissions(java.lang.String token, java.lang.String profileId, java.lang.String[] missionIds) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void unAssignOrganizationFromUnits(java.lang.String token, java.lang.String organization, lu.hitec.pss.soap.ds.in._10_x.UnitId[] unitIds) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void unAssignUnitFromOrganizations(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.UnitId unitId, java.lang.String[] organizations) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void unAssignInternalIdsFromUnit(java.lang.String token, lu.hitec.pss.soap.ds.in._10_x.InternalId[] internalIds, lu.hitec.pss.soap.ds.in._10_x.UnitId unitId) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void unAssignProfileFromUsers(java.lang.String token, java.lang.String profileId, java.lang.String[] userIds) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
    public void updateMyDashboardWidgets(java.lang.String token, java.lang.String widgets) throws java.rmi.RemoteException, lu.hitec.pss.soap.ds.in._10_x.AuthorizationException, lu.hitec.pss.soap.ds.in._10_x.AuthenticationException, lu.hitec.pss.soap.ds.in._10_x.ResourceNotFoundException;
}
